eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka

spring:
  application:
    name: api-gateway
  cloud.gateway:
    default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
#zuul:
#  routes:
#    starship-service:
#      path: /starship-service/**
#      serviceId: starship-service
#  okhttp:
#    enabled: true

ribbon:
  eureka:
    enabled: true
  OkToRetryOnAllOperations: true
